// <auto-generated />
namespace POSApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class new14 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new14));
        
        string IMigrationMetadata.Id
        {
            get { return "201811050458144_new-14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
