//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POSApp.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Branch.
        /// </summary>
        public static string AddBranch {
            get {
                return ResourceManager.GetString("AddBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add client.
        /// </summary>
        public static string Addclient {
            get {
                return ResourceManager.GetString("Addclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer.
        /// </summary>
        public static string AddCustomer {
            get {
                return ResourceManager.GetString("AddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Department.
        /// </summary>
        public static string AddDepartment {
            get {
                return ResourceManager.GetString("AddDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Designation.
        /// </summary>
        public static string AddDesignation {
            get {
                return ResourceManager.GetString("AddDesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Device.
        /// </summary>
        public static string AddDevice {
            get {
                return ResourceManager.GetString("AddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        public static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Expense.
        /// </summary>
        public static string AddExpense {
            get {
                return ResourceManager.GetString("AddExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Purchase  Order.
        /// </summary>
        public static string AddPurchaseOrder {
            get {
                return ResourceManager.GetString("AddPurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add shifts.
        /// </summary>
        public static string Addshifts {
            get {
                return ResourceManager.GetString("Addshifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add size.
        /// </summary>
        public static string addsize {
            get {
                return ResourceManager.GetString("addsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Supplier.
        /// </summary>
        public static string AddSupplier {
            get {
                return ResourceManager.GetString("AddSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tax.
        /// </summary>
        public static string AddTax {
            get {
                return ResourceManager.GetString("AddTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add unit.
        /// </summary>
        public static string Addunit {
            get {
                return ResourceManager.GetString("Addunit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add warehouse.
        /// </summary>
        public static string addwarehouse {
            get {
                return ResourceManager.GetString("addwarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent income.
        /// </summary>
        public static string Agentincome {
            get {
                return ResourceManager.GetString("Agentincome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppVersion.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Data.
        /// </summary>
        public static string BasicData {
            get {
                return ResourceManager.GetString("BasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches sales.
        /// </summary>
        public static string Branchessales {
            get {
                return ResourceManager.GetString("Branchessales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches timely sales.
        /// </summary>
        public static string branchestimelysales {
            get {
                return ResourceManager.GetString("branchestimelysales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cashiers income.
        /// </summary>
        public static string cashiersincome {
            get {
                return ResourceManager.GetString("cashiersincome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories Sales.
        /// </summary>
        public static string CategoriesSales {
            get {
                return ResourceManager.GetString("CategoriesSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryId.
        /// </summary>
        public static string CategoryId {
            get {
                return ResourceManager.GetString("CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category list.
        /// </summary>
        public static string categorylist {
            get {
                return ResourceManager.GetString("categorylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combos sales.
        /// </summary>
        public static string Combossales {
            get {
                return ResourceManager.GetString("Combossales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission.
        /// </summary>
        public static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption.
        /// </summary>
        public static string consumption {
            get {
                return ResourceManager.GetString("consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Price.
        /// </summary>
        public static string CostPrice {
            get {
                return ResourceManager.GetString("CostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryOfOrigin.
        /// </summary>
        public static string CountryOfOrigin {
            get {
                return ResourceManager.GetString("CountryOfOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupons.
        /// </summary>
        public static string coupons {
            get {
                return ResourceManager.GetString("coupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        public static string Createdat {
            get {
                return ResourceManager.GetString("Createdat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created at status actions.
        /// </summary>
        public static string createdatstatusactions {
            get {
                return ResourceManager.GetString("createdatstatusactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string customers {
            get {
                return ResourceManager.GetString("customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers sales.
        /// </summary>
        public static string Customerssales {
            get {
                return ResourceManager.GetString("Customerssales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Expense.
        /// </summary>
        public static string DailyExpense {
            get {
                return ResourceManager.GetString("DailyExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily purchases.
        /// </summary>
        public static string Dailypurchases {
            get {
                return ResourceManager.GetString("Dailypurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Sales.
        /// </summary>
        public static string DailySales {
            get {
                return ResourceManager.GetString("DailySales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Form.
        /// </summary>
        public static string DateForm {
            get {
                return ResourceManager.GetString("DateForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date to.
        /// </summary>
        public static string Dateto {
            get {
                return ResourceManager.GetString("Dateto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        public static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Code.
        /// </summary>
        public static string DeviceCode {
            get {
                return ResourceManager.GetString("DeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Import.
        /// </summary>
        public static string DeviceImport {
            get {
                return ResourceManager.GetString("DeviceImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Code.
        /// </summary>
        public static string DiscountCode {
            get {
                return ResourceManager.GetString("DiscountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded Date.
        /// </summary>
        public static string DownloadedDate {
            get {
                return ResourceManager.GetString("DownloadedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Templete.
        /// </summary>
        public static string DownloadTemplete {
            get {
                return ResourceManager.GetString("DownloadTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drivers income.
        /// </summary>
        public static string driversincome {
            get {
                return ResourceManager.GetString("driversincome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeId.
        /// </summary>
        public static string EmployeeId {
            get {
                return ResourceManager.GetString("EmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees sales.
        /// </summary>
        public static string Employeessales {
            get {
                return ResourceManager.GetString("Employeessales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees shifts.
        /// </summary>
        public static string employeesshifts {
            get {
                return ResourceManager.GetString("employeesshifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Address.
        /// </summary>
        public static string EnterAddress {
            get {
                return ResourceManager.GetString("EnterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter App Version.
        /// </summary>
        public static string EnterAppVersion {
            get {
                return ResourceManager.GetString("EnterAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Barcode.
        /// </summary>
        public static string EnterBarcode {
            get {
                return ResourceManager.GetString("EnterBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Brand.
        /// </summary>
        public static string EnterBrand {
            get {
                return ResourceManager.GetString("EnterBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter City Name.
        /// </summary>
        public static string EnterCityName {
            get {
                return ResourceManager.GetString("EnterCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Code.
        /// </summary>
        public static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Color.
        /// </summary>
        public static string EnterColor {
            get {
                return ResourceManager.GetString("EnterColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Contact No..
        /// </summary>
        public static string EnterContactNo {
            get {
                return ResourceManager.GetString("EnterContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Cost.
        /// </summary>
        public static string EnterCost {
            get {
                return ResourceManager.GetString("EnterCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Country Of Origin.
        /// </summary>
        public static string EnterCountryOfOrigin {
            get {
                return ResourceManager.GetString("EnterCountryOfOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Description.
        /// </summary>
        public static string EnterDescription {
            get {
                return ResourceManager.GetString("EnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Device Code.
        /// </summary>
        public static string EnterDeviceCode {
            get {
                return ResourceManager.GetString("EnterDeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email Address.
        /// </summary>
        public static string EnterEmailAddress {
            get {
                return ResourceManager.GetString("EnterEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter License.
        /// </summary>
        public static string EnterLicense {
            get {
                return ResourceManager.GetString("EnterLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Quantity.
        /// </summary>
        public static string EnterQuantity {
            get {
                return ResourceManager.GetString("EnterQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Remarks.
        /// </summary>
        public static string EnterRemarks {
            get {
                return ResourceManager.GetString("EnterRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter State Name.
        /// </summary>
        public static string EnterStateName {
            get {
                return ResourceManager.GetString("EnterStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanses.
        /// </summary>
        public static string Expanses {
            get {
                return ResourceManager.GetString("Expanses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Head.
        /// </summary>
        public static string ExpenseHead {
            get {
                return ResourceManager.GetString("ExpenseHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Head Id.
        /// </summary>
        public static string ExpenseHeadId {
            get {
                return ResourceManager.GetString("ExpenseHeadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Head List.
        /// </summary>
        public static string ExpenseHeadList {
            get {
                return ResourceManager.GetString("ExpenseHeadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Heads.
        /// </summary>
        public static string ExpenseHeads {
            get {
                return ResourceManager.GetString("ExpenseHeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expiration.
        /// </summary>
        public static string expiration {
            get {
                return ResourceManager.GetString("expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting.
        /// </summary>
        public static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Username / Password?.
        /// </summary>
        public static string ForgotUsernamePassword {
            get {
                return ResourceManager.GetString("ForgotUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Hour.
        /// </summary>
        public static string FromHour {
            get {
                return ResourceManager.GetString("FromHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report.
        /// </summary>
        public static string GenerateReport {
            get {
                return ResourceManager.GetString("GenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data.
        /// </summary>
        public static string ImportData {
            get {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Excel Data.
        /// </summary>
        public static string ImportExcelData {
            get {
                return ResourceManager.GetString("ImportExcelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Login Attempt.
        /// </summary>
        public static string invalidloginattempt {
            get {
                return ResourceManager.GetString("invalidloginattempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory control.
        /// </summary>
        public static string inventorycontrol {
            get {
                return ResourceManager.GetString("inventorycontrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory items recipe.
        /// </summary>
        public static string inventoryitemsrecipe {
            get {
                return ResourceManager.GetString("inventoryitemsrecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory item total cost.
        /// </summary>
        public static string inventoryitemtotalcost {
            get {
                return ResourceManager.GetString("inventoryitemtotalcost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory reports.
        /// </summary>
        public static string inventoryreports {
            get {
                return ResourceManager.GetString("inventoryreports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Transactions.
        /// </summary>
        public static string inventorytransactions {
            get {
                return ResourceManager.GetString("inventorytransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsOperational.
        /// </summary>
        public static string IsOperational {
            get {
                return ResourceManager.GetString("IsOperational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Percentage.
        /// </summary>
        public static string IsPercentage {
            get {
                return ResourceManager.GetString("IsPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Taxable.
        /// </summary>
        public static string IsTaxable {
            get {
                return ResourceManager.GetString("IsTaxable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item cost.
        /// </summary>
        public static string itemcost {
            get {
                return ResourceManager.GetString("itemcost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item history.
        /// </summary>
        public static string itemhistory {
            get {
                return ResourceManager.GetString("itemhistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining Date.
        /// </summary>
        public static string JoiningDate {
            get {
                return ResourceManager.GetString("JoiningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to levels.
        /// </summary>
        public static string levels {
            get {
                return ResourceManager.GetString("levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations sales.
        /// </summary>
        public static string Locationssales {
            get {
                return ResourceManager.GetString("Locationssales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Login.
        /// </summary>
        public static string MemberLogin {
            get {
                return ResourceManager.GetString("MemberLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Sales.
        /// </summary>
        public static string MenuSales {
            get {
                return ResourceManager.GetString("MenuSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous Report.
        /// </summary>
        public static string MiscellaneousReport {
            get {
                return ResourceManager.GetString("MiscellaneousReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiers.
        /// </summary>
        public static string Modifiers {
            get {
                return ResourceManager.GetString("Modifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modifiers recipe.
        /// </summary>
        public static string modifiersrecipe {
            get {
                return ResourceManager.GetString("modifiersrecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiers sales.
        /// </summary>
        public static string modifierssales {
            get {
                return ResourceManager.GetString("modifierssales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Sales:.
        /// </summary>
        public static string MonthlySales {
            get {
                return ResourceManager.GetString("MonthlySales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Report.
        /// </summary>
        public static string Myreport {
            get {
                return ResourceManager.GetString("Myreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Purchase Order.
        /// </summary>
        public static string NewPurchaseOrder {
            get {
                return ResourceManager.GetString("NewPurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available in table.
        /// </summary>
        public static string Nodataavailableintable {
            get {
                return ResourceManager.GetString("Nodataavailableintable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File Chosen.
        /// </summary>
        public static string NoFileChosen {
            get {
                return ResourceManager.GetString("NoFileChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found.
        /// </summary>
        public static string Norecordsfound {
            get {
                return ResourceManager.GetString("Norecordsfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpeningAmount.
        /// </summary>
        public static string OpeningAmount {
            get {
                return ResourceManager.GetString("OpeningAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationDate.
        /// </summary>
        public static string OperationDate {
            get {
                return ResourceManager.GetString("OperationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string orders {
            get {
                return ResourceManager.GetString("orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders discounts.
        /// </summary>
        public static string ordersdiscounts {
            get {
                return ResourceManager.GetString("ordersdiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order type sales.
        /// </summary>
        public static string ordertypesales {
            get {
                return ResourceManager.GetString("ordertypesales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentMethod.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment methods.
        /// </summary>
        public static string paymentmethods {
            get {
                return ResourceManager.GetString("paymentmethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment methods timely sales.
        /// </summary>
        public static string paymentmethodstimelysales {
            get {
                return ResourceManager.GetString("paymentmethodstimelysales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending transfers.
        /// </summary>
        public static string pendingtransfers {
            get {
                return ResourceManager.GetString("pendingtransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhysicalAmount.
        /// </summary>
        public static string PhysicalAmount {
            get {
                return ResourceManager.GetString("PhysicalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item in the list.
        /// </summary>
        public static string Pleaseselectanteminthelist {
            get {
                return ResourceManager.GetString("Pleaseselectanteminthelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Cloud.
        /// </summary>
        public static string POSCloud {
            get {
                return ResourceManager.GetString("POSCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Terminal.
        /// </summary>
        public static string posterminal {
            get {
                return ResourceManager.GetString("posterminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCT CATEGORIES.
        /// </summary>
        public static string PRODUCTCATEGORIES {
            get {
                return ResourceManager.GetString("PRODUCTCATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product code.
        /// </summary>
        public static string Productcode {
            get {
                return ResourceManager.GetString("Productcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Details.
        /// </summary>
        public static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product List.
        /// </summary>
        public static string ProductList {
            get {
                return ResourceManager.GetString("ProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product modifiers sales.
        /// </summary>
        public static string productmodifierssales {
            get {
                return ResourceManager.GetString("productmodifierssales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product returns.
        /// </summary>
        public static string productreturns {
            get {
                return ResourceManager.GetString("productreturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Sales.
        /// </summary>
        public static string ProductSales {
            get {
                return ResourceManager.GetString("ProductSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products/Services.
        /// </summary>
        public static string ProductsandServices {
            get {
                return ResourceManager.GetString("ProductsandServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products cost.
        /// </summary>
        public static string productscost {
            get {
                return ResourceManager.GetString("productscost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products discounts.
        /// </summary>
        public static string productsdiscounts {
            get {
                return ResourceManager.GetString("productsdiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product sizes by order type sales.
        /// </summary>
        public static string Productsizesbyordertypesales {
            get {
                return ResourceManager.GetString("Productsizesbyordertypesales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Sizes Discounts.
        /// </summary>
        public static string productsizesdiscounts {
            get {
                return ResourceManager.GetString("productsizesdiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product sizes sales.
        /// </summary>
        public static string Productsizessales {
            get {
                return ResourceManager.GetString("Productsizessales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Prepration Time.
        /// </summary>
        public static string ProductsPreprationTime {
            get {
                return ResourceManager.GetString("ProductsPreprationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products recipe.
        /// </summary>
        public static string productsrecipe {
            get {
                return ResourceManager.GetString("productsrecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products stock.
        /// </summary>
        public static string productsstock {
            get {
                return ResourceManager.GetString("productsstock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products timely sales.
        /// </summary>
        public static string productstimelysales {
            get {
                return ResourceManager.GetString("productstimelysales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        public static string PurchaseOrder {
            get {
                return ResourceManager.GetString("PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase order Date.
        /// </summary>
        public static string PurchaseorderDate {
            get {
                return ResourceManager.GetString("PurchaseorderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order List.
        /// </summary>
        public static string PurchaseOrderList {
            get {
                return ResourceManager.GetString("PurchaseOrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Orders.
        /// </summary>
        public static string purchaseorders {
            get {
                return ResourceManager.GetString("purchaseorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases.
        /// </summary>
        public static string Purchases {
            get {
                return ResourceManager.GetString("Purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchases per supplier.
        /// </summary>
        public static string purchasespersupplier {
            get {
                return ResourceManager.GetString("purchasespersupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Orders.
        /// </summary>
        public static string SaleOrders {
            get {
                return ResourceManager.GetString("SaleOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order.
        /// </summary>
        public static string SalesOrder {
            get {
                return ResourceManager.GetString("SalesOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales report.
        /// </summary>
        public static string Salesreport {
            get {
                return ResourceManager.GetString("Salesreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Option.
        /// </summary>
        public static string SelectanOption {
            get {
                return ResourceManager.GetString("SelectanOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Employee.
        /// </summary>
        public static string SelectEmployee {
            get {
                return ResourceManager.GetString("SelectEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Expense Head.
        /// </summary>
        public static string SelectExpenseHead {
            get {
                return ResourceManager.GetString("SelectExpenseHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semi finished item cost.
        /// </summary>
        public static string semifinisheditemcost {
            get {
                return ResourceManager.GetString("semifinisheditemcost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semi finished item levels.
        /// </summary>
        public static string semifinisheditemlevels {
            get {
                return ResourceManager.GetString("semifinisheditemlevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIFTS.
        /// </summary>
        public static string SHIFTS {
            get {
                return ResourceManager.GetString("SHIFTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show  entries.
        /// </summary>
        public static string Showentries {
            get {
                return ResourceManager.GetString("Showentries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing 1 to 1 of 1 entries.
        /// </summary>
        public static string Showing1to1of1entries {
            get {
                return ResourceManager.GetString("Showing1to1of1entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size.
        /// </summary>
        public static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshots.
        /// </summary>
        public static string snapshots {
            get {
                return ResourceManager.GetString("snapshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Taking.
        /// </summary>
        public static string stocktaking {
            get {
                return ResourceManager.GetString("stocktaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemAmount.
        /// </summary>
        public static string SystemAmount {
            get {
                return ResourceManager.GetString("SystemAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables sales.
        /// </summary>
        public static string tablessales {
            get {
                return ResourceManager.GetString("tablessales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taxes.
        /// </summary>
        public static string taxes {
            get {
                return ResourceManager.GetString("taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxId.
        /// </summary>
        public static string TaxId {
            get {
                return ResourceManager.GetString("TaxId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to till logs.
        /// </summary>
        public static string tilllogs {
            get {
                return ResourceManager.GetString("tilllogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till Operation.
        /// </summary>
        public static string TillOperation {
            get {
                return ResourceManager.GetString("TillOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till Operations.
        /// </summary>
        public static string tilloperations {
            get {
                return ResourceManager.GetString("tilloperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TillOperationType.
        /// </summary>
        public static string TillOperationType {
            get {
                return ResourceManager.GetString("TillOperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Hour.
        /// </summary>
        public static string ToHour {
            get {
                return ResourceManager.GetString("ToHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total purchases.
        /// </summary>
        public static string totalpurchases {
            get {
                return ResourceManager.GetString("totalpurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Refunds.
        /// </summary>
        public static string TotalRefunds {
            get {
                return ResourceManager.GetString("TotalRefunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total transfers.
        /// </summary>
        public static string totaltransfers {
            get {
                return ResourceManager.GetString("totaltransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Items.
        /// </summary>
        public static string TransactionItems {
            get {
                return ResourceManager.GetString("TransactionItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unit Code.
        /// </summary>
        public static string unitCode {
            get {
                return ResourceManager.GetString("unitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitId.
        /// </summary>
        public static string UnitId {
            get {
                return ResourceManager.GetString("UnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitPrice.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to void reasons.
        /// </summary>
        public static string voidreasons {
            get {
                return ResourceManager.GetString("voidreasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiters income.
        /// </summary>
        public static string waitersincome {
            get {
                return ResourceManager.GetString("waitersincome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk in Customer.
        /// </summary>
        public static string WalkinCustomer {
            get {
                return ResourceManager.GetString("WalkinCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warehouse.
        /// </summary>
        public static string warehouse {
            get {
                return ResourceManager.GetString("warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly Sales vs Expenses.
        /// </summary>
        public static string YearlySalesvsExpenses {
            get {
                return ResourceManager.GetString("YearlySalesvsExpenses", resourceCulture);
            }
        }
    }
}
